import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster"
import { Suspense } from "react";
import { OgNav } from "@/components/ognav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Professor App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      >
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
      <>
      <div className="md:hidden">
        
      </div>
      <div className="hidden flex-col md:flex">
        <OgNav/>

            <Suspense>
            {children}
            </Suspense>
        {/* </OgNav> */}
        </div>
        </>
          </ThemeProvider>
          <Toaster />

      </body>
    </html>
  );
}
