import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster"
import { Suspense } from "react";
import { MainNav } from "@/components/main-nav";
import { UserNav } from "@/components/user-nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Professor App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      >
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
      <>
      <div className="md:hidden">
        
      </div>
      <div className="hidden flex-col md:flex">
        <div className="border-b">
          <div className="flex h-16 items-center px-4">
            {/* <TeamSwitcher /> */}
            <MainNav className="mx-6" />
            <div className="ml-auto flex items-center space-x-4">
              {/* <Search /> */}
              <UserNav />
            </div>
          </div>
        </div>
            <Suspense>
            {children}
            </Suspense>
        </div>
        </>
          </ThemeProvider>
          <Toaster />

      </body>
    </html>
  );
}
